---
name: Acme-PM-Erlangen-SteffenW-BuildTest
version: 0.001
author:
  - 'Steffen Winkler, E<cpan@steffen-winkler.de>;'
abstract: create a CPAN Module using Module::Build on Win32-Systems
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Test::More: '>= 0'
  Tie::Scalar: '>= 0'
  perl: 5.6.1
provides:
  Acme::PM::Erlangen::SteffenW::BuildTest:
    file: lib/Acme/PM/Erlangen/SteffenW/BuildTest.pm
    version: 0.001
generated_by: Module::Build version 0.2801
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
